---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-volume
  labels:
    type: local
    app: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
